export const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'customer' CHECK(role IN ('customer','admin')),
    basu_status TEXT NOT NULL DEFAULT 'unverified' CHECK(basu_status IN ('unverified','pending','verified','rejected')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS equipment (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    capacity INTEGER NOT NULL CHECK(capacity >= 0),
    published INTEGER NOT NULL DEFAULT 1 CHECK(published IN (0,1)),
    public_price_thousands INTEGER,
    basu_price_thousands INTEGER,
    accent TEXT NOT NULL,
    source_ref TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS price_tiers (
    id TEXT PRIMARY KEY,
    equipment_id TEXT NOT NULL REFERENCES equipment(id),
    min_quantity INTEGER NOT NULL,
    max_quantity INTEGER NOT NULL,
    priority INTEGER NOT NULL,
    public_price_thousands INTEGER,
    basu_price_thousands INTEGER NOT NULL,
    note TEXT NOT NULL,
    effective_at TEXT NOT NULL,
    UNIQUE(equipment_id, priority)
  )`,
  `CREATE TABLE IF NOT EXISTS blackouts (
    id TEXT PRIMARY KEY,
    equipment_id TEXT REFERENCES equipment(id),
    start_at TEXT NOT NULL,
    end_at TEXT NOT NULL,
    reason TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
    CHECK(start_at < end_at)
  )`,
  `CREATE TABLE IF NOT EXISTS bookings (
    id TEXT PRIMARY KEY,
    reference TEXT NOT NULL UNIQUE,
    user_id TEXT NOT NULL REFERENCES users(id),
    audience TEXT NOT NULL CHECK(audience IN ('public','basu')),
    reservation_status TEXT NOT NULL CHECK(reservation_status IN ('draft','held','confirmed','fulfilled','returned','closed','cancelled','expired')),
    payment_status TEXT NOT NULL CHECK(payment_status IN ('not_started','pending','paid','failed','cancelled','partially_refunded','refunded')),
    fulfilment_status TEXT NOT NULL CHECK(fulfilment_status IN ('unscheduled','scheduled','handed_over','returned','missed','cancelled')),
    start_at TEXT NOT NULL,
    end_at TEXT NOT NULL,
    contact_phone TEXT NOT NULL,
    event_title TEXT NOT NULL,
    delivery_method TEXT NOT NULL CHECK(delivery_method IN ('pickup','delivery')),
    delivery_address TEXT NOT NULL DEFAULT '',
    subtotal_thousands INTEGER,
    quote_required INTEGER NOT NULL DEFAULT 0 CHECK(quote_required IN (0,1)),
    policy_version TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK(start_at < end_at)
  )`,
  `CREATE TABLE IF NOT EXISTS booking_lines (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    equipment_id TEXT NOT NULL REFERENCES equipment(id),
    item_name_snapshot TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK(quantity > 0),
    unit_price_thousands INTEGER,
    total_thousands INTEGER,
    source_ref TEXT NOT NULL,
    UNIQUE(booking_id, equipment_id)
  )`,
  `CREATE TABLE IF NOT EXISTS delivery_quotes (
    booking_id TEXT PRIMARY KEY REFERENCES bookings(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','finalized')),
    fee_thousands INTEGER CHECK(fee_thousands IS NULL OR fee_thousands >= 0),
    reviewed_by_user_id TEXT REFERENCES users(id),
    reviewed_at TEXT,
    note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK((status = 'pending' AND fee_thousands IS NULL) OR (status = 'finalized' AND fee_thousands IS NOT NULL))
  )`,
  `CREATE TABLE IF NOT EXISTS booking_events (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    from_value TEXT,
    to_value TEXT,
    actor_user_id TEXT REFERENCES users(id),
    safe_note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS waitlist_entries (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    equipment_id TEXT NOT NULL REFERENCES equipment(id),
    start_at TEXT NOT NULL,
    end_at TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK(quantity > 0),
    status TEXT NOT NULL CHECK(status IN ('waiting','offered','converted','expired','cancelled')),
    offer_expires_at TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS payment_intents (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL REFERENCES bookings(id),
    provider TEXT NOT NULL,
    provider_reference TEXT,
    amount_thousands INTEGER NOT NULL CHECK(amount_thousands >= 0),
    currency TEXT NOT NULL DEFAULT 'TOMAN',
    status TEXT NOT NULL CHECK(status IN ('pending','paid','failed','cancelled','refunded')),
    idempotency_key TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS payment_events (
    id TEXT PRIMARY KEY,
    intent_id TEXT NOT NULL REFERENCES payment_intents(id),
    provider_event_id TEXT NOT NULL UNIQUE,
    event_type TEXT NOT NULL,
    amount_thousands INTEGER NOT NULL,
    signature_verified INTEGER NOT NULL CHECK(signature_verified IN (0,1)),
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS delivery_slots (
    id TEXT PRIMARY KEY,
    start_at TEXT NOT NULL,
    end_at TEXT NOT NULL,
    capacity INTEGER NOT NULL CHECK(capacity > 0),
    active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
    label TEXT NOT NULL,
    CHECK(start_at < end_at)
  )`,
  `CREATE TABLE IF NOT EXISTS fulfilments (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL UNIQUE REFERENCES bookings(id),
    slot_id TEXT REFERENCES delivery_slots(id),
    assignee TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL CHECK(status IN ('unscheduled','scheduled','handed_over','returned','missed','cancelled')),
    safe_note TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS handoff_checklists (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL REFERENCES bookings(id),
    phase TEXT NOT NULL CHECK(phase IN ('handoff','return')),
    condition_summary TEXT NOT NULL,
    confirmed_by_user_id TEXT NOT NULL REFERENCES users(id),
    damage_thousands INTEGER NOT NULL DEFAULT 0 CHECK(damage_thousands >= 0),
    created_at TEXT NOT NULL,
    UNIQUE(booking_id, phase)
  )`,
  `CREATE TABLE IF NOT EXISTS media_objects (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL REFERENCES bookings(id),
    owner_user_id TEXT NOT NULL REFERENCES users(id),
    object_key TEXT NOT NULL UNIQUE,
    purpose TEXT NOT NULL CHECK(purpose IN ('handoff','return','damage')),
    content_type TEXT NOT NULL,
    byte_length INTEGER NOT NULL CHECK(byte_length >= 0),
    checksum TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('active','deleted','rejected')),
    retention_until TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS notification_jobs (
    id TEXT PRIMARY KEY,
    booking_id TEXT NOT NULL REFERENCES bookings(id),
    channel TEXT NOT NULL CHECK(channel IN ('in_app','email','sms')),
    template TEXT NOT NULL,
    due_at TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('pending','processing','sent','retry','cancelled','blocked_configuration')),
    attempts INTEGER NOT NULL DEFAULT 0,
    dedupe_key TEXT NOT NULL UNIQUE,
    last_error_code TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS audit_events (
    id TEXT PRIMARY KEY,
    actor_user_id TEXT REFERENCES users(id),
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL,
    result_code TEXT NOT NULL,
    correlation_id TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS idempotency_keys (
    key TEXT PRIMARY KEY,
    actor_user_id TEXT NOT NULL REFERENCES users(id),
    action TEXT NOT NULL,
    result_json TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS policy_versions (
    id TEXT PRIMARY KEY,
    policy_type TEXT NOT NULL,
    version TEXT NOT NULL,
    config_json TEXT NOT NULL,
    effective_at TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
    UNIQUE(policy_type, version)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_bookings_user_created ON bookings(user_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_bookings_interval_status ON bookings(start_at, end_at, reservation_status)`,
  `CREATE INDEX IF NOT EXISTS idx_booking_lines_equipment ON booking_lines(equipment_id, booking_id)`,
  `CREATE INDEX IF NOT EXISTS idx_delivery_quotes_status ON delivery_quotes(status, updated_at)`,
  `CREATE INDEX IF NOT EXISTS idx_waitlist_equipment_status ON waitlist_entries(equipment_id, status, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_due_status ON notification_jobs(status, due_at)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_events(entity_type, entity_id, created_at)`,
] as const;
