import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { SiteFooter, SiteHeader } from '@/app/components/site-header';
import { CATALOG, findCatalogItem, formatTomanFromThousands } from '@/app/lib/catalog';
export function generateStaticParams(){return CATALOG.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const item=findCatalogItem((await params).slug);if(!item)return{title:'تجهیز پیدا نشد | باسو',openGraph:{images:[]},twitter:{images:[]}};return{title:`${item.name} | باسو`,description:item.description,openGraph:{title:item.name,description:item.description,images:[]},twitter:{title:item.name,description:item.description,images:[]}}}
export default async function EquipmentDetail({params}:{params:Promise<{slug:string}>}){const item=findCatalogItem((await params).slug);if(!item)notFound();return <main><SiteHeader/><section className="detail-shell"><div className={`detail-art accent-${item.accent}`}><span>{item.art}</span><i>{item.shortName}</i></div><div className="detail-copy"><span className="eyebrow"><i/> {item.category==='gown'?'قیمت پلکانی':'آماده رزرو'}</span><h1>{item.name}</h1><p>{item.description}</p><div className="detail-prices"><div><span>قیمت بوعلی</span><b>{formatTomanFromThousands(item.basuThousands)}</b></div><div><span>قیمت آزاد</span><b>{formatTomanFromThousands(item.publicThousands)}</b></div></div>{item.tiers&&<div className="tier-table"><b>قیمت هر لباس بر اساس تعداد</b>{item.tiers.map((tier)=><div key={tier.priority}><span>{tier.note}</span><i>{formatTomanFromThousands(tier.basuThousands)}</i><i>{formatTomanFromThousands(tier.publicThousands)}</i></div>)}</div>}<Link className="primary-action" href={`/book?item=${item.id}`}>رزرو این تجهیز <span>←</span></Link></div></section><SiteFooter/></main>}

